import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case system, de, en, es
    var id: String { rawValue }

    var label: String {
        switch self {
        case .system: return L.s("lang.system")
        case .de: return "Deutsch"
        case .en: return "English"
        case .es: return "Español"
        }
    }

    static let supportedCodes = ["de", "en", "es"]

    /// Effective language code (de/en/es), system fallback → en.
    ///
    /// Deliberately multi-pronged: the app ships no `.lproj` folders, just a
    /// runtime table. Depending on how the system negotiates the language,
    /// sometimes one source is populated, sometimes another — so we ask all
    /// four in order instead of relying on `Locale.preferredLanguages`.
    var effectiveCode: String {
        if self != .system { return rawValue }
        var candidates = Bundle.main.preferredLocalizations
        candidates += Locale.preferredLanguages
        candidates += UserDefaults.standard.stringArray(forKey: "AppleLanguages") ?? []
        if let current = Locale.current.language.languageCode?.identifier {
            candidates.append(current)
        }
        for lang in candidates {
            let code = String(lang.prefix(2)).lowercased()
            if Self.supportedCodes.contains(code) { return code }
        }
        return "en"
    }
}

enum AppPresence: String, CaseIterable, Identifiable {
    case menuBar, dock, both
    var id: String { rawValue }
    var label: String {
        switch self {
        case .menuBar: return L.s("presence.menuBar")
        case .dock: return L.s("presence.dock")
        case .both: return L.s("presence.both")
        }
    }
}

/// Central translation table. `L.s("key")` — fallback: English, then the key.
enum L {
    /// Set by AppState at launch and on language changes.
    nonisolated(unsafe) static var code: String = "en"

    static func s(_ key: String) -> String {
        tables[code]?[key] ?? tables["en"]?[key] ?? key
    }

    static func f(_ key: String, _ args: CVarArg...) -> String {
        String(format: s(key), arguments: args)
    }

    private static let tables: [String: [String: String]] = [

        // ─────────────────────────── GERMAN ───────────────────────────
        "de": [
            "lang.system": "Systemsprache",
            "presence.menuBar": "Nur Menüleiste",
            "presence.dock": "Nur Dock",
            "presence.both": "Menüleiste und Dock",

            // Menu
            "menu.noEvents": "Keine Termine in den nächsten 48 h 🎉",
            "menu.setupCalendar": "Kalenderzugriff einrichten…",
            "menu.upcoming": "Nächste Termine",
            "menu.upcomingHint": "Klick = Alarm sofort zeigen (z. B. früher beitreten)",
            "menu.skipNext": "Nächsten Termin stummschalten",
            "menu.quickReminder": "Eigene Erinnerung…",
            "menu.testAlarm": "Testalarm zeigen",
            "menu.resume": "Erinnerungen fortsetzen (pausiert bis %@)",
            "menu.pause": "Pausieren",
            "menu.pause1h": "Für 1 Stunde",
            "menu.pauseTomorrow": "Bis morgen früh",
            "menu.settings": "Einstellungen…",
            "menu.feedback": "Feedback senden…",
            "menu.quit": "Unforget beenden",
            "badge.now": "jetzt!",
            "badge.inMin": "%d Min",
            "badge.inH": "in %d h",
            "menu.rel.inMin": "in %d Min",
            "menu.rel.now": "jetzt",

            // Overlay
            "overlay.status.final": "GLEICH GEHT'S LOS",
            "overlay.status.missed": "LÄUFT BEREITS",
            "overlay.status.snooze": "RUNDE ZWEI",
            "overlay.untilStart": "bis es losgeht",
            "overlay.running": "läuft bereits",
            "overlay.label.time": "TERMIN UM",
            "overlay.label.place": "TREFFPUNKT",
            "overlay.label.mission": "MISSION",
            "overlay.mission.value": "Pünktlich sein 😌",
            "overlay.chip.video": "%@ · Kamera-Haare richten nicht vergessen",
            "overlay.join": "%@ beitreten",
            "overlay.confirm": "Los geht's!",
            "overlay.confirm.missed": "Bin unterwegs!",
            "overlay.snooze": "Noch 2 Minuten",
            "overlay.ignore": "Nicht mehr erinnern (gedrückt halten)",
            "overlay.ignore.a11y": "Für diesen Termin nicht mehr erinnern. Zum Bestätigen gedrückt halten.",
            "overlay.footer": "Unforget — mit 💚 gebaut von Greenstein.Design",

            // Banner
            "banner.snoozed": "Alles klar — ich bin in %d Minuten wieder da. 👋",
            "banner.guarded": "Du bist gerade im Call — ich bleibe dezent und melde mich gleich wieder. 🤫",
            "banner.hardstop": "In 5 Minuten endet dieser Termin — ‚%@' wartet schon. Guter Moment fürs Fazit.",
            "speech.final": "%@ — es geht gleich los.",
            "speech.missed": "%@ läuft bereits.",
            "settings.speech": "Sprachansage (Titel vorlesen)",
            "quick.detected": "Erkannt: %@",
            "settings.exclude": "Termine ausblenden",
            "settings.exclude.keywords": "Stichwörter",
            "settings.exclude.placeholder": "z. B. Fokuszeit, Blocker",
            "settings.exclude.hint": "Termine, deren Titel eines dieser Stichwörter enthält (Komma-getrennt), lösen keinen Alarm aus. Abgelehnte Einladungen überspringen wir automatisch.",
            "settings.guard": "Präsentations-Schutz",
            "settings.guard.enable": "Während Video-Calls nur Banner zeigen",
            "settings.guard.hint": "Wenn gerade ein Meeting mit Video-Link läuft, erscheinen weitere Alarme als dezentes Banner statt Fullscreen — kein Alarm-Auftritt vor versammelter Runde. Danach kommen sie automatisch wieder.",
            "banner.success.title": "Läuft!",
            "banner.skipped": "Alles klar, dafür bleiben wir still. Der Rest läuft normal weiter. 🤫",
            "banner.reminderSet.title": "Alles klar!",
            "banner.reminderSet": "Ich melde mich um %@. Groß. Unübersehbar. 😌",

            // Test alert
            "test.title": "Testalarm 🎉",
            // Demo content (store screenshots)
            "demo.meeting.title": "Design-Review · Q3 Brand Refresh",
            "demo.meeting.notes": "Neue Logo-Entwürfe mitbringen · Sarah zeigt das Farbsystem",
            "demo.missed.title": "Weekly Standup",
            "demo.missed.notes": "Sprint-Ziele · Demo des neuen Onboardings",
            "demo.custom.title": "Pizza aus dem Ofen holen 🍕",
            "test.location": "Genau hier",

            // Settings
            "settings.tab.general": "Allgemein",
            "settings.tab.calendars": "Kalender",
            "settings.tab.personality": "Persönlichkeit",
            "settings.tab.about": "Über",
            // Setup assistant
            "settings.profile": "Profil",
            "setup.step": "Schritt %d von %d",
            "setup.next": "Weiter",
            "setup.back": "Zurück",
            "setup.skip": "Später",
            "setup.finish": "Fertig",
            "setup.intro.hint": "In vier kurzen Schritten ist alles eingestellt. Ändern kannst du später jederzeit alles.",
            "setup.calendar.title": "Kalender freigeben",
            "setup.calendar.lead": "Ein Systemdialog fragt einmal nach Zugriff auf deine Termine. Ohne ihn kann Unforget nichts anzeigen — mit ihm liest es die nächsten 48 Stunden, ausschließlich auf deinem Mac.",
            "setup.when.title": "Wann soll ich mich melden?",
            "setup.when.lead": "Damit abends und am Wochenende Ruhe ist, wenn du das möchtest.",
            "setup.when.from": "Von",
            "setup.when.to": "Bis",
            "profile.always": "Immer",
            "profile.always.note": "Rund um die Uhr, an jedem Tag. Ruhezeiten kannst du zusätzlich in den Einstellungen setzen.",
            "profile.daytime": "Tagsüber",
            "profile.daytime.note": "Nur montags bis freitags im gewählten Zeitfenster. Am Wochenende bleibt es still.",
            "profile.days": "Bestimmte Tage",
            "profile.days.note": "Nur an den Tagen, die du unten auswählst — praktisch für Uni-, Büro- oder Homeoffice-Tage.",
            "setup.stages.title": "Wie früh soll ich dich anstupsen?",
            "setup.stages.lead": "Ab Werk kommt genau ein Alarm, eine Minute vorher. Mehr Vorlauf nur, wenn du ihn brauchst.",
            "setup.stages.hint": "Die kleinste aktive Stufe übernimmt den ganzen Bildschirm, größere melden sich als dezentes Banner. Mindestens eine Stufe bleibt aktiv.",
            "setup.look.title": "Wie soll der Alarm aussehen?",
            "setup.look.lead": "Acht Stile, dazu deine eigene Farbe. Ein Logo kannst du später in den Einstellungen ergänzen.",
            "setup.done.title": "Fast geschafft",
            "setup.done.lead": "Eine Erinnerungs-App, die man erst starten muss, erinnert erfahrungsgemäß schlecht.",
            "settings.tab.appearance": "Aussehen",
            "settings.style": "Grafik-Stil",
            "settings.style.preview": "Stil im Testalarm ansehen",
            "settings.accent": "Akzentfarbe",
            "settings.accent.pick": "Eigene Farbe",
            "settings.accent.reset": "Auf Stil-Standard zurücksetzen",
            "settings.accent.hint": "Die eigene Farbe sticht die Farbe des Stils — für Ring, Rahmen und Schaltflächen.",
            "settings.logo": "Eigenes Logo",
            "settings.logo.pick": "Bild wählen…",
            "settings.logo.clear": "Entfernen",
            "settings.logo.hint": "Das Bild liegt über dem Spruch im Alarm und wird in die App kopiert. Praktisch für Teams oder Schulklassen. PNG, JPEG, TIFF oder PDF bis 3 MB.",
            "settings.logo.tooBig": "Zu groß: %.1f MB. Bitte ein Bild unter 3 MB wählen.",
            "settings.logo.failed": "Das Bild konnte nicht übernommen werden.",
            "style.modern": "Modern",
            "style.modern.note": "Schwarz, grün, geometrisch — der Auslieferungszustand.",
            "style.business": "Business Casual",
            "style.business.note": "Gedeckte Blautöne und Serifen. Fällt im Meeting nicht negativ auf.",
            "style.playful": "Verspielt",
            "style.playful.note": "Runde Formen, warme Farben, ein bisschen Zirkus.",
            "style.kids": "For Kids",
            "style.kids.note": "Dicke Konturen, große Flächen, knallig — für junge Nutzer.",
            "style.pink": "Pink",
            "style.pink.note": "Magenta mit weichem Leuchten. Kompromisslos rosa.",
            "style.mono": "Mono",
            "style.mono.note": "Nur Schwarz und Weiß, keine Rundungen. Maximal ruhig.",
            "style.terminal": "Retro Terminal",
            "style.terminal.note": "Phosphorgrün, Monospace, Rasterzeilen. Für Nostalgiker.",
            "style.sunset": "Sunset",
            "style.sunset.note": "Warme Bernsteintöne, angenehm für müde Augen am Abend.",
            "settings.timing": "Erinnerungszeitpunkt",
            "settings.stage.n": "%d Minuten vorher",
            "settings.stage.1": "1 Minute vorher",
            "settings.followUp": "Nachfassen, wenn der Termin schon läuft",
            "settings.escalation": "Schnellwahl",
            "settings.escalation.hint": "Ab Werk kommt genau ein Alarm — eine Minute vorher, dazu einmal Nachfassen, falls du nicht reagiert hast. Wer mehr Vorlauf braucht, schaltet 5 und 15 Minuten dazu; die kleinste aktive Stufe übernimmt immer den ganzen Bildschirm.",
            "preset.custom": "Eigene Auswahl",
            "preset.single": "Nur ein Alarm (Standard)",
            "preset.standard": "Vorwarnung + Alarm (5/1 Min.)",
            "preset.ramp": "Volle Rampe (15/5/1 Min.)",
            "settings.sound": "Sound",
            "settings.sound.enable": "Sound abspielen",
            "settings.sound.pick": "Klang",
            "settings.sound.nag": "Alle 30 s wiederholen, bis du reagierst",
            "settings.sound.preview": "Probehören",
            "settings.sound.hint": "Sounds starten immer leise und werden sanft lauter — kein Schreckmoment, versprochen.",
            "settings.quiet": "Ruhezeiten",
            "settings.quiet.enable": "Ruhezeiten aktivieren",
            "settings.quiet.from": "Still von",
            "settings.quiet.to": "bis",
            "settings.quiet.hint": "In der Ruhezeit bleiben Kalender-Alarme still. Danach wird nur nachgeholt, was gerade ansteht — nicht, was Stunden her ist. Eigene Erinnerungen klingeln trotzdem: Wer sie bewusst stellt, will sie auch hören.",
            "settings.system": "System",
            "settings.launchAtLogin": "Beim Anmelden starten",
            "settings.presence": "Anzeigen in",
            "settings.language": "Sprache",
            "settings.calendars.title": "Diese Kalender im Auge behalten",
            "settings.calendars.hint": "Google-, Outlook- oder Exchange-Kalender? Einfach in den macOS-Systemeinstellungen unter ‚Internetaccounts' hinzufügen — sie tauchen dann automatisch hier auf.",
            "settings.calendars.noAccess": "Unforget braucht Zugriff auf deinen Kalender, um dich erinnern zu können.",
            "settings.calendars.allow": "Zugriff erlauben",
            "settings.personality.title": "Wie soll Unforget mit dir reden?",
            "settings.personality.tone": "Tonlage",
            "settings.personality.sample": "Kostprobe",
            "settings.personality.more": "Noch eine Kostprobe",
            "settings.personality.hint": "Egal welche Tonlage: Unforget macht sich über die Situation lustig, nie über dich. Kein Schuldgefühl-Gedöns, keine traurige Eule. 💚",
            "intensity.plain": "Sachlich",
            "intensity.friendly": "Freundlich",
            "intensity.cheeky": "Frech",
            "about.version": "Version %@ — frisch geschlüpft 🐣",
            "about.by": "Gebaut mit 💚 von **Greenstein.Design**",
            "about.claim": "Wir bauen Marken, die bleiben —\nund Erinnerungen, die man nicht übersehen kann.",
            "about.tagline": "Für alle, deren Gehirn Besseres zu tun hat,\nals auf die Uhr zu schauen.",
            "about.feedback": "Feedback senden…",

            // Welcome
            "welcome.title": "Hey! Schön, dass du da bist. 👋",
            "welcome.intro": "Unforget sorgt dafür, dass du nie wieder einen Termin verpasst —\nmit Erinnerungen, die den ganzen Bildschirm übernehmen.\nUnübersehbar. Freundlich. Ein kleines bisschen frech.",
            "welcome.granted": "Kalenderzugriff aktiv — alles startklar!",
            "welcome.testButton": "Zeig mir einen Testalarm! 🎉",
            "welcome.autostart.q": "Eine Sache noch: Soll Unforget künftig automatisch mitstarten?\n(Empfohlen — Erinnerungen, die nicht laufen, erinnern erfahrungsgemäß schlecht.)",
            "welcome.autostart.yes": "Ja, automatisch starten",
            "welcome.autostart.no": "Lieber nicht",
            "welcome.done": "Du findest Unforget ab jetzt oben in der Menüleiste (⚡).\nMehr musst du nicht tun — wir melden uns. Versprochen.",
            "welcome.denied": "Kalenderzugriff fehlt noch",
            "welcome.denied.hint": "Bitte in den Systemeinstellungen → Datenschutz & Sicherheit → Kalender\nfür Unforget den vollen Zugriff erlauben.",
            "welcome.openSettings": "Systemeinstellungen öffnen",
            "welcome.ask": "Ein Klick noch: Damit wir dich erinnern können,\nbrauchen wir einen Blick in deinen Kalender.\n(Alles bleibt auf deinem Mac. Ehrenwort.)",
            "welcome.allow": "Kalenderzugriff erlauben",
            "welcome.footer": "Mit 💚 gebaut von Greenstein.Design",
            "welcome.windowTitle": "Willkommen bei Unforget",
            "welcome.tagline": "Nie wieder einen Termin verpassen.",
            "welcome.b1": "Unübersehbar: Fullscreen auf allen Monitoren",
            "welcome.b2": "Freundlich & witzig — nie mit Schuldgefühl",
            "welcome.b3": "100 % privat: alles bleibt auf deinem Mac",

            // QuickReminder
            "quick.windowTitle": "Eigene Erinnerung",
            "quick.title": "Woran sollen wir dich erinnern?",
            "quick.placeholder": "z. B. Pizza aus dem Ofen holen 🍕",
            "quick.in": "In…",
            "quick.at": "Um…",
            "quick.time": "Uhrzeit",
            "quick.minutes": "%d Minuten",
            "quick.hour": "1 Stunde",
            "quick.hours": "%g Stunden",
            "quick.cancel": "Abbrechen",
            "quick.save": "Erinnern!",
            "quick.fallbackTitle": "Erinnerung",

            // Feedback
            "feedback.windowTitle": "Feedback",
            "feedback.title": "Sag uns, was du denkst!",
            "feedback.subtitle": "Dein Feedback geht direkt an Rene — keine Umwege, kein Formular-Nirwana.",
            "feedback.cat.idea": "💡 Idee",
            "feedback.cat.bug": "🐛 Fehler",
            "feedback.cat.love": "💚 Lob",
            "feedback.cat.other": "🤔 Sonstiges",
            "feedback.placeholder": "Was ist dir aufgefallen? Je konkreter, desto besser — aber Stichworte reichen völlig.",
            "feedback.diagnostics": "App-Version und macOS-Version hängen wir automatisch an — mehr nicht.",
            "feedback.cancel": "Abbrechen",
            "feedback.send": "Per Mail senden",
            "feedback.sent.title": "Danke dir! 💚",
            "feedback.sent": "Deine Mail ist vorbereitet — nur noch auf Senden drücken.",
            "feedback.copied.title": "In der Zwischenablage!",
            "feedback.copied": "Kein Mail-Programm gefunden — dein Feedback liegt im Clipboard. Einfach an rene@greenstein.design schicken.",
        ],

        // ─────────────────────────── ENGLISH ───────────────────────────
        "en": [
            "lang.system": "System language",
            "presence.menuBar": "Menu bar only",
            "presence.dock": "Dock only",
            "presence.both": "Menu bar and Dock",

            "menu.noEvents": "No events in the next 48 h 🎉",
            "menu.setupCalendar": "Set up calendar access…",
            "menu.upcoming": "Upcoming events",
            "menu.upcomingHint": "Click = show alert now (e.g. join early)",
            "menu.skipNext": "Mute next event",
            "menu.quickReminder": "Quick reminder…",
            "menu.testAlarm": "Show test alert",
            "menu.resume": "Resume alerts (paused until %@)",
            "menu.pause": "Pause",
            "menu.pause1h": "For 1 hour",
            "menu.pauseTomorrow": "Until tomorrow morning",
            "menu.settings": "Settings…",
            "menu.feedback": "Send feedback…",
            "menu.quit": "Quit Unforget",
            "badge.now": "now!",
            "badge.inMin": "%d min",
            "badge.inH": "in %d h",
            "menu.rel.inMin": "in %d min",
            "menu.rel.now": "now",

            "overlay.status.final": "IT'S ALMOST GO TIME",
            "overlay.status.missed": "ALREADY RUNNING",
            "overlay.status.snooze": "ROUND TWO",
            "overlay.untilStart": "until liftoff",
            "overlay.running": "already running",
            "overlay.label.time": "STARTS AT",
            "overlay.label.place": "MEETING POINT",
            "overlay.label.mission": "MISSION",
            "overlay.mission.value": "Be on time 😌",
            "overlay.chip.video": "%@ · quick camera-hair check recommended",
            "overlay.join": "Join %@",
            "overlay.confirm": "On my way!",
            "overlay.confirm.missed": "Heading in now!",
            "overlay.snooze": "2 more minutes",
            "overlay.ignore": "Stop reminding me (press and hold)",
            "overlay.ignore.a11y": "Stop reminders for this event. Press and hold to confirm.",
            "overlay.footer": "Unforget — built with 💚 by Greenstein.Design",

            "banner.snoozed": "Got it — I'll be back in %d minutes. 👋",
            "banner.guarded": "You're in a call — staying subtle, I'll check back in a moment. 🤫",
            "banner.hardstop": "This event ends in 5 minutes — '%@' is up next. Good moment to wrap up.",
            "speech.final": "%@ is about to start.",
            "speech.missed": "%@ is already running.",
            "settings.speech": "Voice announcement (speak title)",
            "quick.detected": "Detected: %@",
            "settings.exclude": "Exclude events",
            "settings.exclude.keywords": "Keywords",
            "settings.exclude.placeholder": "e.g. focus time, blocker",
            "settings.exclude.hint": "Events whose title contains one of these keywords (comma-separated) won't trigger alerts. Declined invitations are skipped automatically.",
            "settings.guard": "Presentation guard",
            "settings.guard.enable": "Show only banners during video calls",
            "settings.guard.hint": "While a meeting with a video link is running, further alerts appear as a subtle banner instead of full screen — no alarm show in front of the whole team. They return automatically afterwards.",
            "banner.success.title": "Nice!",
            "banner.skipped": "Got it, staying quiet for that one. Everything else runs as usual. 🤫",
            "banner.reminderSet.title": "All set!",
            "banner.reminderSet": "I'll pop up at %@. Big. Unmissable. 😌",

            "test.title": "Test alert 🎉",
            // Demo content (store screenshots)
            "demo.meeting.title": "Design Review · Q3 Brand Refresh",
            "demo.meeting.notes": "Bring the new logo drafts · Sarah presents the color system",
            "demo.missed.title": "Weekly Standup",
            "demo.missed.notes": "Sprint goals · Demo of the new onboarding flow",
            "demo.custom.title": "Take the pizza out of the oven 🍕",
            "test.location": "Right here",

            "settings.tab.general": "General",
            "settings.tab.calendars": "Calendars",
            "settings.tab.personality": "Personality",
            "settings.tab.about": "About",
            // Setup assistant
            "settings.profile": "Profile",
            "setup.step": "Step %d of %d",
            "setup.next": "Continue",
            "setup.back": "Back",
            "setup.skip": "Later",
            "setup.finish": "Done",
            "setup.intro.hint": "Four short steps and you're set. You can change everything later, any time.",
            "setup.calendar.title": "Grant calendar access",
            "setup.calendar.lead": "A system dialog asks once for access to your events. Without it Unforget can't show anything — with it, it reads the next 48 hours, on your Mac only.",
            "setup.when.title": "When should I speak up?",
            "setup.when.lead": "So that evenings and weekends stay quiet, if that's what you want.",
            "setup.when.from": "From",
            "setup.when.to": "To",
            "profile.always": "Always",
            "profile.always.note": "Around the clock, every day. You can still add quiet hours in Settings.",
            "profile.daytime": "Daytime",
            "profile.daytime.note": "Monday to Friday within the chosen window only. Weekends stay silent.",
            "profile.days": "Specific days",
            "profile.days.note": "Only on the days you pick below — handy for campus, office or work-from-home days.",
            "setup.stages.title": "How early should I nudge you?",
            "setup.stages.lead": "Out of the box you get exactly one alert, one minute ahead. More runway only if you need it.",
            "setup.stages.hint": "The smallest active stage takes the whole screen, larger ones arrive as a discreet banner. At least one stage stays on.",
            "setup.look.title": "How should the alert look?",
            "setup.look.lead": "Eight styles plus your own colour. You can add a logo later in Settings.",
            "setup.done.title": "Almost there",
            "setup.done.lead": "A reminder app you have to start yourself is, in our experience, a poor reminder app.",
            "settings.tab.appearance": "Appearance",
            "settings.style": "Graphic style",
            "settings.style.preview": "See the style in a test alert",
            "settings.accent": "Accent colour",
            "settings.accent.pick": "Your own colour",
            "settings.accent.reset": "Reset to the style default",
            "settings.accent.hint": "Your own colour overrides the style colour — for the ring, the border and the buttons.",
            "settings.logo": "Your own logo",
            "settings.logo.pick": "Choose image…",
            "settings.logo.clear": "Remove",
            "settings.logo.hint": "The image sits above the line in the alert and is copied into the app. Handy for teams or school classes. PNG, JPEG, TIFF or PDF up to 3 MB.",
            "settings.logo.tooBig": "Too large: %.1f MB. Please pick an image under 3 MB.",
            "settings.logo.failed": "The image could not be used.",
            "style.modern": "Modern",
            "style.modern.note": "Black, green, geometric — the way it ships.",
            "style.business": "Business Casual",
            "style.business.note": "Muted blues and serifs. Nothing to raise an eyebrow in a meeting.",
            "style.playful": "Playful",
            "style.playful.note": "Round shapes, warm colours, a little bit of circus.",
            "style.kids": "For Kids",
            "style.kids.note": "Thick outlines, big surfaces, loud colours — for younger users.",
            "style.pink": "Pink",
            "style.pink.note": "Magenta with a soft glow. Uncompromisingly pink.",
            "style.mono": "Mono",
            "style.mono.note": "Black and white only, no rounded corners. Maximum calm.",
            "style.terminal": "Retro Terminal",
            "style.terminal.note": "Phosphor green, monospace, scan lines. For the nostalgic.",
            "style.sunset": "Sunset",
            "style.sunset.note": "Warm amber tones, easy on tired eyes in the evening.",
            "settings.timing": "Alert timing",
            "settings.stage.n": "%d minutes before",
            "settings.stage.1": "1 minute before",
            "settings.followUp": "Follow up once the event has started",
            "settings.escalation": "Quick pick",
            "settings.escalation.hint": "Out of the box you get exactly one alert — one minute before, plus a single follow-up if you didn't react. Need more runway? Add 5 and 15 minutes; the smallest active stage always takes the whole screen.",
            "preset.custom": "Custom selection",
            "preset.single": "Single alert (default)",
            "preset.standard": "Heads-up + alert (5/1 min)",
            "preset.ramp": "Full ramp (15/5/1 min)",
            "settings.sound": "Sound",
            "settings.sound.enable": "Play sound",
            "settings.sound.pick": "Tone",
            "settings.sound.nag": "Repeat every 30 s until you react",
            "settings.sound.preview": "Preview",
            "settings.sound.hint": "Sounds always start quiet and fade in gently — no jump scares, promise.",
            "settings.quiet": "Quiet hours",
            "settings.quiet.enable": "Enable quiet hours",
            "settings.quiet.from": "Quiet from",
            "settings.quiet.to": "until",
            "settings.quiet.hint": "During quiet hours calendar alerts stay silent. Afterwards Unforget only catches up on what's happening right now — not what's hours old. Your own reminders still ring: if you set one on purpose, you want to hear it.",
            "settings.system": "System",
            "settings.launchAtLogin": "Launch at login",
            "settings.presence": "Show in",
            "settings.language": "Language",
            "settings.calendars.title": "Keep an eye on these calendars",
            "settings.calendars.hint": "Google, Outlook or Exchange calendars? Just add them in macOS System Settings under 'Internet Accounts' — they'll show up here automatically.",
            "settings.calendars.noAccess": "Unforget needs access to your calendar to remind you.",
            "settings.calendars.allow": "Allow access",
            "settings.personality.title": "How should Unforget talk to you?",
            "settings.personality.tone": "Tone",
            "settings.personality.sample": "Sample",
            "settings.personality.more": "Another sample",
            "settings.personality.hint": "Whatever the tone: Unforget jokes about the situation, never about you. No guilt trips, no sad owl. 💚",
            "intensity.plain": "Plain",
            "intensity.friendly": "Friendly",
            "intensity.cheeky": "Cheeky",
            "about.version": "Version %@ — freshly hatched 🐣",
            "about.by": "Built with 💚 by **Greenstein.Design**",
            "about.claim": "We build brands that last —\nand reminders you can't miss.",
            "about.tagline": "For everyone whose brain has better things to do\nthan watch the clock.",
            "about.feedback": "Send feedback…",

            "welcome.title": "Hey! Great to have you here. 👋",
            "welcome.intro": "Unforget makes sure you never miss an event again —\nwith reminders that take over your whole screen.\nUnmissable. Friendly. A tiny bit cheeky.",
            "welcome.granted": "Calendar access active — ready to go!",
            "welcome.testButton": "Show me a test alert! 🎉",
            "welcome.autostart.q": "One more thing: should Unforget start automatically with your Mac?\n(Recommended — reminders that aren't running are famously bad at reminding.)",
            "welcome.autostart.yes": "Yes, start automatically",
            "welcome.autostart.no": "Rather not",
            "welcome.done": "You'll find Unforget up in the menu bar (⚡).\nThat's all — we'll take it from here. Promise.",
            "welcome.denied": "Calendar access still missing",
            "welcome.denied.hint": "Please allow full access for Unforget in\nSystem Settings → Privacy & Security → Calendars.",
            "welcome.openSettings": "Open System Settings",
            "welcome.ask": "One click to go: to remind you,\nwe need a peek at your calendar.\n(Everything stays on your Mac. Scout's honor.)",
            "welcome.allow": "Allow calendar access",
            "welcome.footer": "Built with 💚 by Greenstein.Design",
            "welcome.windowTitle": "Welcome to Unforget",
            "welcome.tagline": "Never miss another meeting.",
            "welcome.b1": "Unmissable: full screen on every monitor",
            "welcome.b2": "Friendly & funny — never guilt-trippy",
            "welcome.b3": "100% private: everything stays on your Mac",

            "quick.windowTitle": "Quick reminder",
            "quick.title": "What should we remind you about?",
            "quick.placeholder": "e.g. take the pizza out of the oven 🍕",
            "quick.in": "In…",
            "quick.at": "At…",
            "quick.time": "Time",
            "quick.minutes": "%d minutes",
            "quick.hour": "1 hour",
            "quick.hours": "%g hours",
            "quick.cancel": "Cancel",
            "quick.save": "Remind me!",
            "quick.fallbackTitle": "Reminder",

            "feedback.windowTitle": "Feedback",
            "feedback.title": "Tell us what you think!",
            "feedback.subtitle": "Your feedback goes straight to Rene — no detours, no form limbo.",
            "feedback.cat.idea": "💡 Idea",
            "feedback.cat.bug": "🐛 Bug",
            "feedback.cat.love": "💚 Love",
            "feedback.cat.other": "🤔 Other",
            "feedback.placeholder": "What did you notice? The more specific the better — but bullet points are totally fine.",
            "feedback.diagnostics": "We automatically attach the app version and macOS version — nothing else.",
            "feedback.cancel": "Cancel",
            "feedback.send": "Send via email",
            "feedback.sent.title": "Thank you! 💚",
            "feedback.sent": "Your email is ready — just hit send.",
            "feedback.copied.title": "Copied to clipboard!",
            "feedback.copied": "No email app found — your feedback is in the clipboard. Just send it to rene@greenstein.design.",
        ],

        // ─────────────────────────── SPANISH ───────────────────────────
        "es": [
            "lang.system": "Idioma del sistema",
            "presence.menuBar": "Solo barra de menús",
            "presence.dock": "Solo Dock",
            "presence.both": "Barra de menús y Dock",

            "menu.noEvents": "Sin eventos en las próximas 48 h 🎉",
            "menu.setupCalendar": "Configurar acceso al calendario…",
            "menu.upcoming": "Próximos eventos",
            "menu.upcomingHint": "Clic = mostrar alerta ahora (p. ej. unirse antes)",
            "menu.skipNext": "Silenciar el próximo evento",
            "menu.quickReminder": "Recordatorio rápido…",
            "menu.testAlarm": "Mostrar alerta de prueba",
            "menu.resume": "Reanudar alertas (en pausa hasta %@)",
            "menu.pause": "Pausar",
            "menu.pause1h": "Durante 1 hora",
            "menu.pauseTomorrow": "Hasta mañana por la mañana",
            "menu.settings": "Ajustes…",
            "menu.feedback": "Enviar comentarios…",
            "menu.quit": "Salir de Unforget",
            "badge.now": "¡ya!",
            "badge.inMin": "%d min",
            "badge.inH": "en %d h",
            "menu.rel.inMin": "en %d min",
            "menu.rel.now": "ahora",

            "overlay.status.final": "YA CASI ES LA HORA",
            "overlay.status.missed": "YA HA EMPEZADO",
            "overlay.status.snooze": "SEGUNDA RONDA",
            "overlay.untilStart": "para el despegue",
            "overlay.running": "ya en curso",
            "overlay.label.time": "EMPIEZA A LAS",
            "overlay.label.place": "PUNTO DE ENCUENTRO",
            "overlay.label.mission": "MISIÓN",
            "overlay.mission.value": "Llegar a tiempo 😌",
            "overlay.chip.video": "%@ · revisa el pelo para la cámara",
            "overlay.join": "Unirse a %@",
            "overlay.confirm": "¡Voy!",
            "overlay.confirm.missed": "¡Entrando ya!",
            "overlay.snooze": "2 minutos más",
            "overlay.ignore": "No recordar más (mantener pulsado)",
            "overlay.ignore.a11y": "No recordar más este evento. Mantén pulsado para confirmar.",
            "overlay.footer": "Unforget — hecho con 💚 por Greenstein.Design",

            "banner.snoozed": "Vale — vuelvo en %d minutos. 👋",
            "banner.guarded": "Estás en una llamada — me quedo discreto y vuelvo en un momento. 🤫",
            "banner.hardstop": "Este evento termina en 5 minutos — después viene '%@'. Buen momento para cerrar.",
            "speech.final": "%@ está a punto de empezar.",
            "speech.missed": "%@ ya está en curso.",
            "settings.speech": "Anuncio de voz (leer el título)",
            "quick.detected": "Detectado: %@",
            "settings.exclude": "Excluir eventos",
            "settings.exclude.keywords": "Palabras clave",
            "settings.exclude.placeholder": "p. ej. tiempo de foco, bloqueo",
            "settings.exclude.hint": "Los eventos cuyo título contenga una de estas palabras (separadas por comas) no activan alertas. Las invitaciones rechazadas se omiten automáticamente.",
            "settings.guard": "Protección de presentación",
            "settings.guard.enable": "Solo banners durante videollamadas",
            "settings.guard.hint": "Mientras haya una reunión con enlace de vídeo en curso, las demás alertas aparecen como banner discreto en vez de pantalla completa. Después vuelven automáticamente.",
            "banner.success.title": "¡Genial!",
            "banner.skipped": "Entendido, con ese nos callamos. Todo lo demás sigue normal. 🤫",
            "banner.reminderSet.title": "¡Listo!",
            "banner.reminderSet": "Apareceré a las %@. En grande. Imposible de ignorar. 😌",

            "test.title": "Alerta de prueba 🎉",
            // Demo content (store screenshots)
            "demo.meeting.title": "Revisión de diseño · Q3 Brand Refresh",
            "demo.meeting.notes": "Trae los nuevos logos · Sarah presenta el sistema de color",
            "demo.missed.title": "Daily del equipo",
            "demo.missed.notes": "Objetivos del sprint · Demo del nuevo onboarding",
            "demo.custom.title": "Sacar la pizza del horno 🍕",
            "test.location": "Aquí mismo",

            "settings.tab.general": "General",
            "settings.tab.calendars": "Calendarios",
            "settings.tab.personality": "Personalidad",
            "settings.tab.about": "Acerca de",
            // Setup assistant
            "settings.profile": "Perfil",
            "setup.step": "Paso %d de %d",
            "setup.next": "Continuar",
            "setup.back": "Atrás",
            "setup.skip": "Más tarde",
            "setup.finish": "Listo",
            "setup.intro.hint": "En cuatro pasos cortos está todo configurado. Podrás cambiarlo cuando quieras.",
            "setup.calendar.title": "Dar acceso al calendario",
            "setup.calendar.lead": "Un diálogo del sistema pide una vez acceso a tus eventos. Sin él Unforget no puede mostrar nada — con él lee las próximas 48 horas, solo en tu Mac.",
            "setup.when.title": "¿Cuándo debo avisarte?",
            "setup.when.lead": "Para que por la noche y el fin de semana haya calma, si así lo quieres.",
            "setup.when.from": "Desde",
            "setup.when.to": "Hasta",
            "profile.always": "Siempre",
            "profile.always.note": "A todas horas, todos los días. Las horas de silencio puedes añadirlas aparte en los ajustes.",
            "profile.daytime": "De día",
            "profile.daytime.note": "Solo de lunes a viernes dentro de la franja elegida. El fin de semana se queda callado.",
            "profile.days": "Días concretos",
            "profile.days.note": "Solo los días que marques abajo — práctico para días de universidad, oficina o teletrabajo.",
            "setup.stages.title": "¿Con cuánta antelación te aviso?",
            "setup.stages.lead": "De fábrica llega exactamente una alerta, un minuto antes. Más margen solo si lo necesitas.",
            "setup.stages.hint": "La etapa activa más pequeña ocupa toda la pantalla; las mayores llegan como aviso discreto. Al menos una etapa queda activa.",
            "setup.look.title": "¿Qué aspecto debe tener la alerta?",
            "setup.look.lead": "Ocho estilos y tu propio color. El logo puedes añadirlo después en los ajustes.",
            "setup.done.title": "Casi listo",
            "setup.done.lead": "Una app de recordatorios que hay que arrancar a mano recuerda bastante mal, por experiencia.",
            "settings.tab.appearance": "Aspecto",
            "settings.style": "Estilo gráfico",
            "settings.style.preview": "Ver el estilo en una alerta de prueba",
            "settings.accent": "Color de acento",
            "settings.accent.pick": "Color propio",
            "settings.accent.reset": "Volver al color del estilo",
            "settings.accent.hint": "Tu color sustituye al del estilo — en el anillo, el borde y los botones.",
            "settings.logo": "Logo propio",
            "settings.logo.pick": "Elegir imagen…",
            "settings.logo.clear": "Quitar",
            "settings.logo.hint": "La imagen se coloca sobre la frase en la alerta y se copia dentro de la app. Práctico para equipos o clases. PNG, JPEG, TIFF o PDF de hasta 3 MB.",
            "settings.logo.tooBig": "Demasiado grande: %.1f MB. Elige una imagen de menos de 3 MB.",
            "settings.logo.failed": "No se pudo usar la imagen.",
            "style.modern": "Moderno",
            "style.modern.note": "Negro, verde, geométrico — tal y como viene de serie.",
            "style.business": "Business Casual",
            "style.business.note": "Azules apagados y serifas. No desentona en una reunión.",
            "style.playful": "Divertido",
            "style.playful.note": "Formas redondas, colores cálidos, un puntito de circo.",
            "style.kids": "For Kids",
            "style.kids.note": "Contornos gruesos, superficies grandes, colores vivos — para los más jóvenes.",
            "style.pink": "Rosa",
            "style.pink.note": "Magenta con un brillo suave. Rosa sin concesiones.",
            "style.mono": "Mono",
            "style.mono.note": "Solo blanco y negro, sin esquinas redondeadas. Máxima calma.",
            "style.terminal": "Retro Terminal",
            "style.terminal.note": "Verde fósforo, monoespaciada, líneas de barrido. Para nostálgicos.",
            "style.sunset": "Sunset",
            "style.sunset.note": "Tonos ámbar cálidos, agradables para ojos cansados por la noche.",
            "settings.timing": "Momento del aviso",
            "settings.stage.n": "%d minutos antes",
            "settings.stage.1": "1 minuto antes",
            "settings.followUp": "Insistir cuando el evento ya ha empezado",
            "settings.escalation": "Selección rápida",
            "settings.escalation.hint": "De fábrica llega exactamente una alerta — un minuto antes, más un recordatorio si no reaccionaste. ¿Necesitas más margen? Añade 5 y 15 minutos; la etapa activa más pequeña siempre ocupa toda la pantalla.",
            "preset.custom": "Selección propia",
            "preset.single": "Una sola alerta (estándar)",
            "preset.standard": "Preaviso + alerta (5/1 min)",
            "preset.ramp": "Rampa completa (15/5/1 min)",
            "settings.sound": "Sonido",
            "settings.sound.enable": "Reproducir sonido",
            "settings.sound.pick": "Tono",
            "settings.sound.nag": "Repetir cada 30 s hasta que reacciones",
            "settings.sound.preview": "Escuchar",
            "settings.sound.hint": "Los sonidos empiezan bajitos y suben con suavidad — sin sustos, prometido.",
            "settings.quiet": "Horas de silencio",
            "settings.quiet.enable": "Activar horas de silencio",
            "settings.quiet.from": "Silencio desde",
            "settings.quiet.to": "hasta",
            "settings.quiet.hint": "Durante las horas de silencio los avisos del calendario se callan. Después Unforget solo recupera lo que está pasando ahora — no lo de hace horas. Tus propios recordatorios sí suenan: si los pones a propósito, quieres oírlos.",
            "settings.system": "Sistema",
            "settings.launchAtLogin": "Abrir al iniciar sesión",
            "settings.presence": "Mostrar en",
            "settings.language": "Idioma",
            "settings.calendars.title": "Vigilar estos calendarios",
            "settings.calendars.hint": "¿Calendarios de Google, Outlook o Exchange? Añádelos en Ajustes del Sistema → 'Cuentas de internet' — aparecerán aquí automáticamente.",
            "settings.calendars.noAccess": "Unforget necesita acceso a tu calendario para recordarte.",
            "settings.calendars.allow": "Permitir acceso",
            "settings.personality.title": "¿Cómo quieres que te hable Unforget?",
            "settings.personality.tone": "Tono",
            "settings.personality.sample": "Muestra",
            "settings.personality.more": "Otra muestra",
            "settings.personality.hint": "Sea cual sea el tono: Unforget bromea sobre la situación, nunca sobre ti. Sin culpas, sin búho triste. 💚",
            "intensity.plain": "Neutro",
            "intensity.friendly": "Amable",
            "intensity.cheeky": "Descarado",
            "about.version": "Versión %@ — recién salida del cascarón 🐣",
            "about.by": "Hecho con 💚 por **Greenstein.Design**",
            "about.claim": "Construimos marcas que perduran —\ny recordatorios imposibles de ignorar.",
            "about.tagline": "Para quienes su cerebro tiene cosas mejores que hacer\nque mirar el reloj.",
            "about.feedback": "Enviar comentarios…",

            "welcome.title": "¡Hola! Qué bien tenerte aquí. 👋",
            "welcome.intro": "Unforget hace que no vuelvas a perderte un evento —\ncon recordatorios que ocupan toda la pantalla.\nImposibles de ignorar. Amables. Un poquito descarados.",
            "welcome.granted": "Acceso al calendario activo — ¡todo listo!",
            "welcome.testButton": "¡Enséñame una alerta de prueba! 🎉",
            "welcome.autostart.q": "Una cosa más: ¿Unforget debería abrirse automáticamente con tu Mac?\n(Recomendado — los recordatorios apagados recuerdan fatal.)",
            "welcome.autostart.yes": "Sí, abrir automáticamente",
            "welcome.autostart.no": "Mejor no",
            "welcome.done": "Encontrarás Unforget arriba en la barra de menús (⚡).\nNada más que hacer — nosotros nos encargamos. Prometido.",
            "welcome.denied": "Falta el acceso al calendario",
            "welcome.denied.hint": "Permite el acceso completo para Unforget en\nAjustes del Sistema → Privacidad y seguridad → Calendarios.",
            "welcome.openSettings": "Abrir Ajustes del Sistema",
            "welcome.ask": "Un clic más: para recordarte,\nnecesitamos echar un vistazo a tu calendario.\n(Todo se queda en tu Mac. Palabra.)",
            "welcome.allow": "Permitir acceso al calendario",
            "welcome.footer": "Hecho con 💚 por Greenstein.Design",
            "welcome.windowTitle": "Bienvenido a Unforget",
            "welcome.tagline": "No vuelvas a perderte una reunión.",
            "welcome.b1": "Imposible de ignorar: pantalla completa en todos los monitores",
            "welcome.b2": "Amable y divertido — nunca con culpas",
            "welcome.b3": "100 % privado: todo se queda en tu Mac",

            "quick.windowTitle": "Recordatorio rápido",
            "quick.title": "¿Qué te recordamos?",
            "quick.placeholder": "p. ej. sacar la pizza del horno 🍕",
            "quick.in": "En…",
            "quick.at": "A las…",
            "quick.time": "Hora",
            "quick.minutes": "%d minutos",
            "quick.hour": "1 hora",
            "quick.hours": "%g horas",
            "quick.cancel": "Cancelar",
            "quick.save": "¡Recuérdamelo!",
            "quick.fallbackTitle": "Recordatorio",

            "feedback.windowTitle": "Comentarios",
            "feedback.title": "¡Cuéntanos qué piensas!",
            "feedback.subtitle": "Tus comentarios van directos a Rene — sin rodeos, sin limbo de formularios.",
            "feedback.cat.idea": "💡 Idea",
            "feedback.cat.bug": "🐛 Error",
            "feedback.cat.love": "💚 Elogio",
            "feedback.cat.other": "🤔 Otro",
            "feedback.placeholder": "¿Qué has notado? Cuanto más concreto mejor — pero con palabras clave basta.",
            "feedback.diagnostics": "Adjuntamos automáticamente la versión de la app y de macOS — nada más.",
            "feedback.cancel": "Cancelar",
            "feedback.send": "Enviar por correo",
            "feedback.sent.title": "¡Gracias! 💚",
            "feedback.sent": "Tu correo está listo — solo falta pulsar enviar.",
            "feedback.copied.title": "¡Copiado al portapapeles!",
            "feedback.copied": "No hay app de correo — tus comentarios están en el portapapeles. Envíalos a rene@greenstein.design.",
        ],
    ]
}
